import { HttpClient } from "@angular/common/http";
import { Inject, Injectable, Optional } from "@angular/core";
import { MusicMakerClient } from "./server-client";

import { ServerHelper } from "./server-helper";

// Server clients are code generated by NSwag studio
// As a team, we should not directly edit code generated in src\app\duo\core\services\server-clients.ts
// By extending the client, we can apply custom code on top of NSwag API code
@Injectable({
  providedIn: 'root'
})
export class MusicMakerService extends MusicMakerClient
{
  constructor(httpClient: HttpClient)
  {
    super(httpClient, ServerHelper.getApiUrl())
  }
}
